name: Notify Claude for PR Review

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  notify-claude:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check if PR needs Claude review
        id: needs_review
        run: |
          pr_author="${{ github.event.pull_request.user.login }}"
          pr_title="${{ github.event.pull_request.title }}"
          
          echo "PR Author: $pr_author"
          echo "PR Title: $pr_title"
          
          # PRs that should get Claude review:
          # 1. Dependabot PRs (dependency updates)
          # 2. Version bump PRs from devops-mindhive
          # 3. Documentation PRs from devops-mindhive
          # 4. PRs with [claude-review] tag
          
          needs_review=false
          
          if [[ "$pr_author" == "dependabot[bot]" ]] || \
             [[ "$pr_author" == "devops-mindhive" && "$pr_title" =~ ^(release|chore|docs): ]] || \
             [[ "$pr_title" =~ \[claude-review\] ]]; then
            needs_review=true
          fi
          
          echo "needs_review=$needs_review" >> $GITHUB_OUTPUT
          
          if [[ "$needs_review" == "true" ]]; then
            echo "✅ PR needs Claude review"
          else
            echo "❌ PR does not need automatic Claude review"
          fi

      - name: Request Claude review
        if: steps.needs_review.outputs.needs_review == 'true'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "@claude Please review this PR for code quality, security, and compatibility. If everything looks good, approve and merge it."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}