name: Semantic Release

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual release'
        required: false
        default: 'Manual release'

permissions:
  contents: write
  packages: write
  pull-requests: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: semantic-release
      cancel-in-progress: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.SEMANTIC_RELEASE_TOKEN || secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true
        virtualenvs-path: .venv

    - name: Install dependencies
      run: |
        poetry install --with dev

    - name: Run comprehensive quality checks
      run: |
        poetry run black --check src/ tests/
        poetry run ruff check src/ tests/
        poetry run mypy src/ --strict --no-warn-no-return
        poetry run bandit -r src/ -f txt -c .bandit

    - name: Run full test suite
      run: |
        poetry run pytest -n 2 --timeout=120 --cov=src --cov-report=term-missing --cov-report=xml --cov-fail-under=85

    - name: Check for release-worthy changes
      id: check_changes
      run: |
        # Check if there are any commits since the last tag that would trigger a release
        LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
        if [ -n "$LAST_TAG" ]; then
          COMMITS_SINCE_TAG=$(git log --oneline $LAST_TAG..HEAD | wc -l)
          RELEASE_WORTHY=$(git log $LAST_TAG..HEAD --grep="^feat" --grep="^fix" --grep="^perf" --grep="BREAKING CHANGE" --oneline | wc -l)
        else
          COMMITS_SINCE_TAG=1
          RELEASE_WORTHY=1
        fi
        
        echo "commits_since_tag=$COMMITS_SINCE_TAG" >> $GITHUB_OUTPUT
        echo "release_worthy=$RELEASE_WORTHY" >> $GITHUB_OUTPUT
        echo "last_tag=$LAST_TAG" >> $GITHUB_OUTPUT
        
        if [ "$RELEASE_WORTHY" -gt 0 ]; then
          echo "Found release-worthy changes since $LAST_TAG"
        else
          echo "No release-worthy changes found since $LAST_TAG"
        fi

    - name: Build packages
      if: steps.check_changes.outputs.release_worthy > 0 || github.event_name == 'workflow_dispatch'
      run: |
        poetry run python -m build

    - name: Run semantic-release version
      if: steps.check_changes.outputs.release_worthy > 0 || github.event_name == 'workflow_dispatch'
      env:
        GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN || secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        poetry run semantic-release version --skip-build

    - name: Check if packages exist after semantic-release
      if: steps.check_changes.outputs.release_worthy > 0 || github.event_name == 'workflow_dispatch'
      run: |
        if [ -d "dist" ] && [ "$(ls -A dist/)" ]; then
          echo "✅ Packages exist in dist/"
          ls -la dist/
          echo "packages_exist=true" >> $GITHUB_ENV
        else
          echo "❌ No packages found, semantic-release may not have triggered a release"
          echo "packages_exist=false" >> $GITHUB_ENV
        fi

    - name: Publish to PyPI with twine
      if: (steps.check_changes.outputs.release_worthy > 0 || github.event_name == 'workflow_dispatch') && env.packages_exist == 'true'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        echo "🚀 Publishing to PyPI with twine..."
        if [ -z "$TWINE_PASSWORD" ]; then
          echo "❌ PYPI_API_TOKEN secret not configured"
          exit 1
        fi
        poetry run twine check dist/*
        poetry run twine upload --username "$TWINE_USERNAME" --password "$TWINE_PASSWORD" dist/* --verbose

    - name: Run semantic-release publish (GitHub release only)
      if: steps.check_changes.outputs.release_worthy > 0 || github.event_name == 'workflow_dispatch'
      env:
        GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN || secrets.GITHUB_TOKEN }}
      run: |
        echo "📝 Creating GitHub release with semantic-release..."
        poetry run semantic-release publish

    - name: Get release version
      if: success() && (steps.check_changes.outputs.release_worthy > 0 || github.event_name == 'workflow_dispatch')
      id: get_version
      run: |
        # Get the latest tag as the released version
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
        echo "released_version=$LATEST_TAG" >> $GITHUB_OUTPUT
        echo "Released version: $LATEST_TAG"

    - name: Sync version to staging branch
      if: success() && steps.get_version.outputs.released_version != ''
      env:
        GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN || secrets.GITHUB_TOKEN }}
      run: |
        echo "🔄 Syncing main to staging branch..."
        
        # Fetch all branches
        git fetch origin staging:staging || echo "Staging branch doesn't exist, skipping"
        
        if git show-ref --verify --quiet refs/heads/staging; then
          # Switch to staging and merge main
          git checkout staging
          git merge main --no-edit || {
            echo "⚠️ Merge conflict detected, creating PR instead"
            git merge --abort
            gh pr create \
              --title "chore: sync version ${{ steps.get_version.outputs.released_version }} from main to staging" \
              --body "Automated sync of semantic release version ${{ steps.get_version.outputs.released_version }} from main branch" \
              --base staging \
              --head main \
              --label "automated,version-sync" || echo "PR may already exist"
          } && {
            echo "✅ Successfully merged main into staging"
            git push origin staging || echo "Failed to push to staging"
          }
        else
          echo "ℹ️ Staging branch doesn't exist, skipping sync"
        fi

    - name: Sync version to develop branch  
      if: success() && steps.get_version.outputs.released_version != ''
      env:
        GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN || secrets.GITHUB_TOKEN }}
      run: |
        echo "🔄 Syncing main to develop branch..."
        
        # Fetch all branches
        git fetch origin develop:develop || echo "Develop branch doesn't exist, skipping"
        
        if git show-ref --verify --quiet refs/heads/develop; then
          # Switch to develop and merge main
          git checkout develop
          git merge main --no-edit || {
            echo "⚠️ Merge conflict detected, creating PR instead"
            git merge --abort
            gh pr create \
              --title "chore: sync version ${{ steps.get_version.outputs.released_version }} from main to develop" \
              --body "Automated sync of semantic release version ${{ steps.get_version.outputs.released_version }} from main branch" \
              --base develop \
              --head main \
              --label "automated,version-sync" || echo "PR may already exist"
          } && {
            echo "✅ Successfully merged main into develop"
            git push origin develop || echo "Failed to push to develop"
          }
        else
          echo "ℹ️ Develop branch doesn't exist, skipping sync"
        fi

    - name: Create release summary
      if: success()
      run: |
        echo "## 🚀 Release Published" >> $GITHUB_STEP_SUMMARY
        echo "- **Version**: ${{ steps.get_version.outputs.released_version }}" >> $GITHUB_STEP_SUMMARY
        echo "- **PyPI**: [pyopenapi-gen ${{ steps.get_version.outputs.released_version }}](https://pypi.org/project/pyopenapi-gen/${{ steps.get_version.outputs.released_version }})" >> $GITHUB_STEP_SUMMARY
        echo "- **GitHub Release**: [Release Notes](https://github.com/mindhiveoy/pyopenapi_gen/releases/tag/${{ steps.get_version.outputs.released_version }})" >> $GITHUB_STEP_SUMMARY
        
        if [ -n "${{ steps.get_version.outputs.released_version }}" ]; then
          echo "- **Branch Sync**: Version synced to staging and develop branches" >> $GITHUB_STEP_SUMMARY
        fi

  notify-completion:
    needs: release
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Report success
      if: needs.release.result == 'success'
      run: |
        echo "✅ Semantic release completed successfully"
        
    - name: Report failure
      if: needs.release.result == 'failure'
      run: |
        echo "❌ Semantic release failed"
        exit 1 