name: Publish to TestPyPI (pre-release)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-testpypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: |
          python -m build
      - name: Run tests
        run: |
          pip install .[dev]
          pytest
      - name: Check distribution with twine
        run: |
          pip install twine
          twine check dist/*
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }} 